# Generated by Django 5.1.1 on 2024-10-07 18:01

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('/nfs/homes/yachaab/Devlopment/django-recipe/recipe/media')),
        ),
    ]
